checkout/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^items', views.items, name='items'),
    url(r'^students', views.students, name='students'),
    url(r'^users', views.users, name='users'),
    url(r'^history', views.checkoutHistory, name='checkoutHistory'),
    url(r'^checkin/(?P<checkout_id>[0-9]+)/$', views.checkin, name='checkin'),
    url(r'^checkout/(?P<item_id>[0-9]+)/$', views.checkout, name='checkout'),
    url(r'^checkout/(?P<item_id>[0-9]+)/other/$', views.othercheckout, name='othercheckout'), #simply handles checkouts that are for users that already have accounts
    url(r'^search_items', views.search_items, name='search_items'),
    url(r'^search_students', views.search_students, name='search_students'),
    url(r'^search_history', views.search_history, name='search_history')
    
]
#

checkyourself/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^checkout/', include('checkout.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page, name='logout'),
]

checkout/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User as AuthUser
# Create your models here.

class User(models.Model):
    student_id = models.CharField(max_length=8,primary_key=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    def __str__(self):
        return self.first_name+" "+self.last_name+": "+str(self.student_id)
    
    #leaving out password for now
    #to add new Item:
    #i = Item(checked_out=False,serial_number="39452",model_number="Raspberry Pi 2",purchase_date=timezone.now(),category="Raspberry Pi",description="Really cool pi")
    
class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    kit_number = models.IntegerField(blank=True, null=True)
    checked_out = models.BooleanField(default=False)
    serial_number = models.CharField(max_length=20) # check whether this is right
    model_number = models.CharField(max_length=50, blank=True, null=True)
    purchase_date = models.DateField('date purchased')
    category = models.CharField(max_length=20)
    description = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
                        
    def __str__(self):
        return self.category

class Checkout(models.Model): #by not specifying a primary key, django will create an autoincrementing field to be the primary key
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    borrower = models.ForeignKey(User,related_name='borrower',null=True,on_delete=models.SET_NULL)
    authorizer = models.ForeignKey(AuthUser,related_name='authorizer',null=True,on_delete=models.SET_NULL)
    checkout_date = models.DateField('checkout date')
    checkin_date = models.DateField('checkin date',null=True,blank=True)
    
    def __str__(self):
        return str(self.checkout_date)
        

checkout/forms.py
from django.forms import *

from .models import User


class OtherCheckoutForm(forms.Form):
    user_id = ModelChoiceField(queryset=User.objects.all().order_by('first_name'))


class CheckoutForm(ModelForm):
    item_id = CharField()

    class Meta:
        model = User
        fields = ['student_id', 'first_name', 'last_name', 'email']

checkout/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Item, User, Checkout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import re
from .forms import CheckoutForm
from .forms import OtherCheckoutForm
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'checkout/index.html', {})

@login_required
def items(request):
    checkouts = {checkout.item.item_id: checkout for checkout in Checkout.objects.filter(checkin_date__isnull=True)}

    items = []
    for item in Item.objects.all().order_by('category'):
        checkout = checkouts.get(item.item_id)
        items.append((item, checkout))

    username = None
    if request.user.is_authenticated():
        username = request.user

    return render(request, 'checkout/listItems.html', {'items': items, 'username': username})

def othercheckout(request, item_id):
    if request.method == 'POST':
        form = OtherCheckoutForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data['user_id'])
            model_instance = data['user_id']
            if request.user.is_authenticated():
                auth_user = request.user
            checkout_instance = Checkout(item=Item.objects.get(item_id=item_id), borrower=model_instance,authorizer=auth_user, checkout_date=timezone.now())
            checkout_instance.save()
        return redirect('items')
    return redirect('items')


def checkout(request, item_id):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

            model_instance = form.save()
            model_instance.save()
            if request.user.is_authenticated():
                auth_user = request.user
            checkout_instance = Checkout(item=Item.objects.get(item_id=int(data['item_id'])), borrower=model_instance,
                                         authorizer=auth_user, checkout_date=timezone.now())

            checkout_instance.save()
            return redirect('items')
        return redirect('items')
    else:
        form = CheckoutForm()
        form2 = OtherCheckoutForm()
        return render(request, 'checkout/checkout.html', {'form': form, 'form2': form2, 'item_id': item_id})


def checkin(request, checkout_id):
    checkout_object = Checkout.objects.get(pk=checkout_id)
    checkout_object.checkin_date = timezone.now()
    checkout_object.item.checked_out = False
    checkout_object.save()
    print("checkin")
    return redirect('items')


def students(request):
    student_list = [student for student in User.objects.all()]
    print(student for student in student_list)
    username = None
    if request.user.is_authenticated():
        username = request.user
    return render(request, 'checkout/listStudents.html', {'students': student_list, 'username': username})


def users(request):
    return HttpResponse("<html><b>This will be the users page")

def checkoutHistory(request):
    username = None
    if request.user.is_authenticated():
        username = request.user
    if (request.GET.get('mybtn')):
        checkouts = Checkout.objects.all().order_by('-checkout_date')
        return render(request, 'checkout/checkoutHistory.html', {'checkouts': checkouts, 'username': username})
    else :
        checkouts = Checkout.objects.all().order_by('checkout_date')
    
    return render(request, 'checkout/checkoutHistory.html',{'checkouts': checkouts, 'username': username})

# code from http://julienphalip.com/post/2825034077/adding-search-to-a-django-site-in-a-snap
def normalize_query(query_string, findterms=re.compile(r'"([^"]+)"|(\S+)').findall, normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in individual keywords, getting rid of unnecessary spaces
        and grouping quoted words together.
        Example:
        
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    
    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 

# code from http://julienphalip.com/post/2825034077/adding-search-to-a-django-site-in-a-snap
def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.
    
    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query
  
# code partially from http://julienphalip.com/post/2825034077/adding-search-to-a-django-site-in-a-snap
def search_items(request):
    username = None
    if request.user.is_authenticated():
        username = request.user
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        
        entry_query = get_query(query_string, ['category', 'model_number', 'kit_number', 'description', 'serial_number'])
        
        entry_query_checkout = get_query(query_string, ['borrower__first_name', 'borrower__last_name', 'checkout_date'])
        
        found_entries = Item.objects.filter(entry_query)
        found_entries_checkout = Checkout.objects.filter(entry_query_checkout)
        
    all_results = []        
    checkouts = {checkout.item.item_id: checkout for checkout in Checkout.objects.filter(checkin_date__isnull=True)}
    items = {item.item_id: item for item in Item.objects.all()}
    resultsArray = list(found_entries)
    checkoutResultsArray = list(found_entries_checkout)
    
    for item in resultsArray:
        checkout = checkouts.get(item.item_id)
        all_results.append((item, checkout))
        
    for checkout in checkoutResultsArray:
        item = items.get(checkout.item_id)
        all_results.append((item, checkout))

    return render(request, 'search/search_items.html',
                          { 'query_string': query_string, 'found_entries': all_results, 'username': username },) 

# code partially from http://julienphalip.com/post/2825034077/adding-search-to-a-django-site-in-a-snap
def search_students(request):
    username = None
    if request.user.is_authenticated():
        username = request.user
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        
        entry_query = get_query(query_string, ['first_name', 'last_name', 'student_id', 'email'])
        
        found_entries = User.objects.filter(entry_query)

    return render(request, 'search/search_students.html',
                          { 'query_string': query_string, 'students': found_entries, 'username': username },)    

def search_history(request):
    username = None
    if request.user.is_authenticated():
        username = request.user
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        
        entry_query = get_query(query_string, ['item__category', 'borrower__first_name', 'borrower__last_name', 'authorizer__first_name', 'authorizer__last_name', 'checkin_date', 'checkout_date', 'item__serial_number', 'item__description', 'item__model_number', 'item__kit_number'])
        
        found_entries = Checkout.objects.filter(entry_query)

    return render(request, 'search/search_history.html',
                          { 'query_string': query_string, 'found_entries': found_entries, 'username': username},)                           

checkout/templates/checkout/checkout.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>Checkout</title>
        <link rel='stylesheet' type='text/css' href="{% static '../../static/style.css' %}" />
    </head>
    <body id="checkoutBody">
        <div id="smallTitle">Existing Student:</div>
        <form method="POST" action ="{%url 'othercheckout' item_id=item_id %}" class="post-form">{% csrf_token %}
        {{form2.user_id}}
            <button type="submit">Select</button>
        </form>

        <div id="smallTitle">New Student:</div>
        <form method="POST" class="post-form">{% csrf_token %}

            <input id="id_item_id" name="item_id" , hidden="false" value="{{item_id}}" readonly/>
            <p>
                <label>Student ID:</label> {{ form.student_id }}
            </p>
            <p>
                <label>First Name:</label> {{ form.first_name}}
            </p>
    		<p>
                <label>Last Name:</label> {{ form.last_name }}
            </p>
            <p>
                <label>Email:</label> {{ form.email }}
            </p>
    		<button type="submit">Add and Select</button>
        </form>
    </body>
</html>

checkout/templates/checkout/checkoutHistory.html
<!DOCTYPE html>
<html>
    <head>
        <title>Checkout History</title>
        <link rel="stylesheet" href="../../static/style.css">
    </head>
    <body>
        
       <header>
            <logo>{% include 'checkout/logo.html' %}</logo><!--
            --><buffer>
                <form id="ascend" action="#" method="get">
                    <input type="submit" value="Sort by Newest Date" name="mybtn">
                </form>
                <form id="descend" action= "{% url 'checkoutHistory' %}" >
                    <button id="descendButton">Sort by Oldest Date</button>
                </form>
            </buffer><!--
            --><navigation>
                {% include 'checkout/navigation.html' with active="checkoutHistory" %}
            </navigation><!--
             --><form id="searchbar" action="/checkout/search_history" method="get">
                    <input type="search" name="q" placeholder="search">
                </form><!--
            -->{% include 'checkout/userAccount.html' %}
             
        </header>
        
        <table id="table">
            
            <thead>
                <tr>
                    <td>Item Type</td>
                    <td>Model</td>
                    <td>Kit #</td>
                    <td>Student Using</td>
                    <td>Authorizer</td>
                    <td>Date Checked Out</td>
                    <td>Date Checked In</td>
                    <td>Description</td>
                    <td>Serial Number</td>

                </tr>
            </thead>
            
            
            <tbody>
                {% for checkout in checkouts %}
                <tr>   
                    <td>{{checkout.item}}</td>
                    <td>{{checkout.item.model_number}}</td>
                    <td>{{checkout.item.kit_number}}</td>
                    <td>{{checkout.borrower.first_name}} {{checkout.borrower.last_name}}</td>
                    <td>{{checkout.authorizer.first_name}} {{checkout.authorizer.last_name}}</td>
                    <td>{{checkout.checkout_date}}</td>
                    <td>{{checkout.checkin_date}}</td>
                    <td>{{checkout.item.description}}</td>
                    <td>{{checkout.item.serial_number}}</td>
                </tr>
                {% endfor %}
            </tbody>

            <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot>            
            
            
            
        </table>
            
            
            
    </body>
</html>

checkout/templates/checkout/index.html
<html>
	<head>
		<title>CheckYourself</title>
		<link rel="stylesheet" href="../../static/style.css">
	</head>
	<body>
		<div id="splashPage">
			<div id="title">CheckYourself</div>
			<a id="loginButton" href="{% url 'items' %}"> Log In</a>
		</div>
	</body>
</html>

checkout/templates/checkout/listItems.html
<!DOCTYPE html>
<html>
	<head>
		<title>Items</title>
		<link rel="stylesheet" href="../../static/style.css">
	</head>
	<body>

		<header>
            <logo>{% include 'checkout/logo.html' %}</logo><!--
  			--><buffer>
  					{% if username.is_staff%}
  						<form target = "_blank" id="addItem" action="{%url 'admin:checkout_item_add' %}" method="get">
	            			<button>Add Item</button>
	        			</form>  
					{% endif %}
    			</buffer><!--
  			--><navigation>
                {% include 'checkout/navigation.html' with active="items" %}
            </navigation><!--
            --><form id="searchbar" action="/checkout/search_items" method="get">
                    <input type="search" name="q" placeholder="search">
                </form><!--
  			-->{% include 'checkout/userAccount.html' %}
        </header>
	    
		<table id="table">
		
			<thead> 
				<tr>
					<td>Check in/out</td>
					<td>Item Type</td>
					<td>Model</td>
					<td>Kit #</td>
					<td>Student Using</td>
					<td>Date Checked Out</td>
					<td>Description</td>
					<td>Serial Number</td>
				</tr>
			</thead>
	          
	        <tbody>  
		        {% for item in items %}

				<tr>
			        <td  style="text-align:center"> 
			        	{%if item.1 != None %}
				        	<form  action="{%url 'checkin' checkout_id=item.1.pk%}" method="post">
				        		<button type="button submit">Check in</button>
				        		{% csrf_token %}
				        	</form>
						{%else%}			
							<form action="{%url 'checkout' item_id=item.0.item_id %}" method="get">
								<button type = "button submit"> Check out</button>
								{% csrf_token %}
							</form>
						{%endif%}
					</td>
					<td>{{item.0.category}}</td>
					<td>{{item.0.model_number}}</td>
					<td>{{item.0.kit_number}}</td>
					<td>{{item.1.borrower.first_name}} {{item.1.borrower.last_name}}</td>
			        <td>{{item.1.checkout_date}}</td>
			        <td>{{item.0.description}}</td>
					<td>{{item.0.serial_number}}</td>
		        </tr>
		        {% endfor %}
	        </tbody>

	         <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot> 
	    
		</table>
	   


	</body>
</html>

checkout/templates/checkout/listStudents.html
<!DOCTYPE html>
<html>
	<head>
		<title>Students</title>
		<link rel="stylesheet" href="../../static/style.css">
	</head>
	<body>
	   
		<header>
            <logo>{% include 'checkout/logo.html' %}</logo><!--
  			--><buffer></buffer><!--
  			--><navigation>
                {% include 'checkout/navigation.html' with active="students" %}
            </navigation><!--
            --><form id="searchbar" action="/checkout/search_students" method="get">
                    <input type="search" name="q" placeholder="search">
            </form><!--
  			-->{% include 'checkout/userAccount.html' %}
        </header>
	    
		<table id="table">
		
			<thead>
				<tr>       
					<td>Student ID</td>
					<td>Name</td>
					<td>Email</td>
				</tr>
			</thead>
	          
	        <tbody>  
		        {% for student in students %}
				<tr>
			        <td>{{student.student_id}}</td>
					<td>{{student.first_name}} {{student.last_name}}</td>
			        <td>{{student.email}}</td>
			        </tr>
		        {% endfor %}
		    </tbody>

		     <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot> 
	    
		</table>
	   


	</body>
</html>

checkout/templates/checkout/logo.html
<a id="home" href="{% url 'items' %}">CheckYourself</a>

checkout/templates/checkout/navigation.html
<ul>	
	<li {% if active = "items" %} class="active" {% endif %}>
		<a href="{% url 'items' %}"> Items </a>
	</li>
	
	<li {% if active = "students" %} class="active" {% endif %}>
		<a href="{% url 'students' %}"> Students </a>
	</li>
	
	<li {% if active = "checkoutHistory" %} class="active" {% endif %}>
		<a href="{% url 'checkoutHistory' %}"> History </a>
	</li>
</ul>

checkout/templates/checkout/userAccount.html
<span id="dropdownParent">
	<a id="accountMenu">
		<span id="arrowDown"></span>
		<span id="firstName"> {{username.first_name}}</span>
		Hello
	</a>
	<div id="dropdown">
		<a id="logoutButton" href="{%url 'logout' %}">Log Out</a>
	</div>
</span>